name: Add addresses to whitelist

on:
  push:
    branches:
    - main

jobs:
  whitelist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Add addresses to whitelist
      run: ./whitelist.py
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}